version: '3'

services:
  slurmmaster:
        image: fractal-slurm:latest
        hostname: slurmmaster
        user: admin
        volumes:
          - /tmp/slurm_share:/tmp/slurm_share:rw
        environment:
                - SLURM_CPUS_ON_NODE=1
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
                - 10022:22
        command: "sacctmgr create account name=test0 && sacctmgr create user test0 account=test0"
  slurmnode1:
        extra_hosts:
          host.docker.internal: host-gateway
        image: rancavil/slurm-node:19.05.5-1
        hostname: slurmnode1
        user: admin
        volumes:
          - /tmp/slurm_share:/tmp/slurm_share:rw
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurmmaster
                  # ports:
                  #   - 50055-50057:50055-50057
                  #   - 54000-55000:54000-55000
        command: "sudo apt-get update && sudo apt-get install -y python3-pip && sudo pip install parsl==1.3.0dev1"
