version: '3'

services:
  slurmmaster:
        image: fractal-slurm-master:latest
        hostname: slurmmaster
        user: admin
        volumes:
          - /tmp/slurm_share:/tmp/slurm_share:rw
        environment:
                - SLURM_CPUS_ON_NODE=1
        ports:
                - 6817:6817
                - 6818:6818
                - 6819:6819
                - 10022:22
  slurmnode1:
        extra_hosts:
          host.docker.internal: host-gateway
        image: fractal-slurm-node:latest
        hostname: slurmnode1
        user: admin
        volumes:
          - /tmp/slurm_share:/tmp/slurm_share:rw
        environment:
                - SLURM_NODENAME=slurmnode1
                - SLURM_CPUS_ON_NODE=1
        links:
                - slurmmaster
