"""Add AccountingRecordSlurm.fractal_job_id

Revision ID: 0016fee8b597
Revises: 0f916383c170
Create Date: 2026-04-20 10:40:00.568094

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0016fee8b597"
down_revision = "0f916383c170"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accountingrecordslurm", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fractal_job_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_accountingrecordslurm_fractal_job_id_jobv2"),
            "jobv2",
            ["fractal_job_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accountingrecordslurm", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_accountingrecordslurm_fractal_job_id_jobv2"),
            type_="foreignkey",
        )
        batch_op.drop_column("fractal_job_id")

    # ### end Alembic commands ###
