"""remove CollectionStateV2

Revision ID: 0267dbc6372b
Revises: 7fe36b294e1a
Create Date: 2024-11-06 13:59:19.026343

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0267dbc6372b"
down_revision = "7fe36b294e1a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collectionstatev2")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collectionstatev2",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "timestamp",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "taskgroupv2_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["taskgroupv2_id"],
            ["taskgroupv2.id"],
            name="fk_collectionstatev2_taskgroupv2_id_taskgroupv2",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_collectionstatev2"),
    )
    # ### end Alembic commands ###
