"""Add dumps to ApplyWorkflow

Revision ID: 0316476e33af
Revises: 99ea79d9e5d2
Create Date: 2023-10-24 14:41:40.563239

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0316476e33af"
down_revision = "99ea79d9e5d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applyworkflow", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "input_dataset_dump",
                sa.JSON(),
                server_default="{}",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "output_dataset_dump",
                sa.JSON(),
                server_default="{}",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "workflow_dump",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            nullable=False,
        )
        batch_op.alter_column(
            "start_timestamp",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=False,
        )
        batch_op.alter_column(
            "input_dataset_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "output_dataset_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "workflow_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applyworkflow", schema=None) as batch_op:
        batch_op.alter_column(
            "workflow_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "output_dataset_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "input_dataset_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "start_timestamp",
            existing_type=postgresql.TIMESTAMP(timezone=True),
            nullable=True,
        )
        batch_op.alter_column(
            "workflow_dump",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        )
        batch_op.drop_column("output_dataset_dump")
        batch_op.drop_column("input_dataset_dump")

    # ### end Alembic commands ###
