"""Drop TaskGroup venv size and files number

Revision ID: 068496367952
Revises: b7477cc98f45
Create Date: 2025-12-10 15:24:47.720796

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "068496367952"
down_revision = "b7477cc98f45"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_column("venv_size_in_kB")
        batch_op.drop_column("venv_file_number")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "venv_file_number",
                sa.INTEGER(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "venv_size_in_kB",
                sa.INTEGER(),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
