"""Drop V1 tables

Revision ID: 077783b86d44
Revises: 7813a4273653
Create Date: 2025-01-29 14:51:32.162988

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "077783b86d44"
down_revision = "7813a4273653"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dataset")
    op.drop_table("project")
    op.drop_table("workflow")
    op.drop_table("workflowtask")
    op.drop_table("state")
    op.drop_table("applyworkflow")
    op.drop_table("task")
    op.drop_table("resource")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resource",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_resource"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_task"),
    )
    op.create_table(
        "applyworkflow",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_applyworkflow"),
    )
    op.create_table(
        "state",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_state"),
    )
    op.create_table(
        "workflowtask",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workflowtask"),
    )
    op.create_table(
        "workflow",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workflow"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_project"),
    )
    op.create_table(
        "dataset",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_dataset"),
    )
    # ### end Alembic commands ###
