"""Remove resource.glob_pattern column

Revision ID: 08665ad9752f
Revises: d9e6283fc947
Create Date: 2023-03-03 13:33:57.780244

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "08665ad9752f"
down_revision = "d9e6283fc947"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource", "glob_pattern")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource", sa.Column("glob_pattern", sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###
