"""Project sharing

Revision ID: 099326684bd9
Revises: e0e717ae2f26
Create Date: 2025-11-18 17:25:43.549056

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "099326684bd9"
down_revision = "e0e717ae2f26"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_owner",
                sa.Boolean(),
                nullable=False,
                # TODO-2.18.1 drop server_default
                server_default=sa.text("true"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_verified",
                sa.Boolean(),
                nullable=False,
                # TODO-2.18.1 drop server_default
                server_default=sa.text("true"),
            )
        )
        batch_op.add_column(
            sa.Column(
                "permissions",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                # TODO-2.18.1 drop server_default
                server_default=sa.text("'rwx'"),
            )
        )
        batch_op.create_index(
            "ix_linkuserprojectv2_one_owner_per_project",
            ["project_id"],
            unique=True,
            postgresql_where=sa.text("is_owner IS true"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_linkuserprojectv2_one_owner_per_project",
            postgresql_where=sa.text("is_owner IS true"),
        )
        batch_op.drop_column("permissions")
        batch_op.drop_column("is_verified")
        batch_op.drop_column("is_owner")

    # ### end Alembic commands ###
