"""historyunit.zarr_urls not nullable

Revision ID: 0c5e3f92c3a8
Revises: 3ddaf7271fc3
Create Date: 2026-09-21 16:49:17.245602

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0c5e3f92c3a8"
down_revision = "3ddaf7271fc3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyunit", schema=None) as batch_op:
        batch_op.alter_column(
            "zarr_urls",
            existing_type=postgresql.ARRAY(sa.VARCHAR()),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyunit", schema=None) as batch_op:
        batch_op.alter_column(
            "zarr_urls",
            existing_type=postgresql.ARRAY(sa.VARCHAR()),
            nullable=True,
        )

    # ### end Alembic commands ###
