"""ApplyWorkflow.working_dir not nullable

Revision ID: 0f126c9c0768
Revises: 4cedeb448a53
Create Date: 2024-01-17 15:53:24.160135

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0f126c9c0768"
down_revision = "4cedeb448a53"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applyworkflow", schema=None) as batch_op:
        batch_op.alter_column(
            "working_dir",
            existing_type=sa.VARCHAR(),
            nullable=False,
            server_default="__UNDEFINED__",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applyworkflow", schema=None) as batch_op:
        batch_op.alter_column(
            "working_dir", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###
