"""Add Profile.pixi_cache_dir

Revision ID: 0f916383c170
Revises: 7226c20dc233
Create Date: 2026-04-08 15:50:29.890726

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f916383c170"
down_revision = "7226c20dc233"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pixi_cache_dir",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_column("pixi_cache_dir")

    # ### end Alembic commands ###
