"""Add ArchiveApplyWorkflow

Revision ID: 16f911059e70
Revises: 04442046e5ca
Create Date: 2023-10-19 12:48:31.242971

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "16f911059e70"
down_revision = "04442046e5ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archivedapplyworkflow",
        sa.Column("input_dataset_dump", sa.JSON(), nullable=False),
        sa.Column("output_dataset_dump", sa.JSON(), nullable=False),
        sa.Column("workflow_dump", sa.JSON(), nullable=False),
        sa.Column(
            "start_timestamp", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("archivedapplyworkflow")
    # ### end Alembic commands ###
