"""Add `prevent_new_submissions`

Revision ID: 1be9f71472cf
Revises: 7910eed4cf97
Create Date: 2025-12-01 16:22:05.337158

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1be9f71472cf"
down_revision = "7910eed4cf97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "prevent_new_submissions",
                sa.BOOLEAN(),
                server_default="false",
                nullable=False,
            ),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_column("prevent_new_submissions")

    # ### end Alembic commands ###
