"""Add description to workflow and description and alias to workflow task

Revision ID: 1bf8785755f9
Revises: 5fb08bf05b14
Create Date: 2026-01-26 09:03:18.396841

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "1bf8785755f9"
down_revision = "5fb08bf05b14"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "alias", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    with op.batch_alter_table("workflowv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowv2", schema=None) as batch_op:
        batch_op.drop_column("description")

    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.drop_column("description")
        batch_op.drop_column("alias")

    # ### end Alembic commands ###
