"""Make versions required

Revision ID: 1c49c1602044
Revises: 92ec661b7f76
Create Date: 2026-06-09 08:40:01.934296

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1c49c1602044"
down_revision = "92ec661b7f76"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.alter_column(
            "version", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "version", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "version", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.alter_column(
            "version", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###
