"""TaskGroup timestamp last_used

Revision ID: 1ced626318d9
Revises: 3082479ac4ea
Create Date: 2024-11-14 09:16:40.805385

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1ced626318d9"
down_revision = "3082479ac4ea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "timestamp_last_used",
                sa.DateTime(timezone=True),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_column("timestamp_last_used")

    # ### end Alembic commands ###
