"""Add accountingrecordslurm.resource_id

Revision ID: 1ef3722b998f
Revises: c0448884a8e9
Create Date: 2026-05-25 14:56:55.444997

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1ef3722b998f"
down_revision = "c0448884a8e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accountingrecordslurm", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("resource_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_accountingrecordslurm_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accountingrecordslurm", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_accountingrecordslurm_resource_id_resource"),
            type_="foreignkey",
        )
        batch_op.drop_column("resource_id")

    # ### end Alembic commands ###
