"""my table

Revision ID: 252c52ccfc87
Revises: 981d588fe248
Create Date: 2025-09-29 17:59:43.898223

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "252c52ccfc87"
down_revision = "981d588fe248"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mytable",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("a", sa.Integer(), nullable=False),
        sa.Column("b", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mytable")),
    )
    with op.batch_alter_table("mytable", schema=None) as batch_op:
        batch_op.create_index(
            "custom_index_name",
            ["a"],
            unique=True,
            postgresql_where=sa.text("b IS true"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("mytable", schema=None) as batch_op:
        batch_op.drop_index(
            "custom_index_name", postgresql_where=sa.text("b IS true")
        )

    op.drop_table("mytable")
    # ### end Alembic commands ###
