"""User project_dirs array

Revision ID: 309b6c111827
Revises: bc0e8b3327a7
Create Date: 2025-11-26 15:12:01.389003

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "309b6c111827"
down_revision = "bc0e8b3327a7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "project_dirs",
                postgresql.ARRAY(sa.String()),
                server_default="{}",
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_column("project_dirs")

    # ### end Alembic commands ###
