"""Add ArchivedApplyWorkflow and ApplyWorkflow.[input-output]_dataset_dump

Revision ID: 3277bd28415f
Revises: 99ea79d9e5d2
Create Date: 2023-10-19 13:21:37.365070

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "3277bd28415f"
down_revision = "99ea79d9e5d2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archivedapplyworkflow",
        sa.Column("input_dataset_dump", sa.JSON(), nullable=False),
        sa.Column("output_dataset_dump", sa.JSON(), nullable=False),
        sa.Column("workflow_dump", sa.JSON(), nullable=False),
        sa.Column(
            "start_timestamp", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("applyworkflow", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "input_dataset_dump",
                sa.JSON(),
                nullable=True,
                server_default=None,
            )
        )
        batch_op.add_column(
            sa.Column(
                "output_dataset_dump",
                sa.JSON(),
                nullable=True,
                server_default=None,
            )
        )
        batch_op.add_column(
            sa.Column(
                "archived",
                sa.Boolean(),
                nullable=False,
                server_default="false",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("applyworkflow", schema=None) as batch_op:
        batch_op.drop_column("archived")
        batch_op.drop_column("output_dataset_dump")
        batch_op.drop_column("input_dataset_dump")

    op.drop_table("archivedapplyworkflow")
    # ### end Alembic commands ###
