"""Drop TaskV2.owner colum

Revision ID: 36a2f8f45949
Revises: 034a469ec2eb
Create Date: 2024-10-29 08:58:38.787110

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "36a2f8f45949"
down_revision = "034a469ec2eb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.drop_column("owner")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "owner", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
