"""Add superuser/guest constraint

Revision ID: 3ddaf7271fc3
Revises: d4027db95431
Create Date: 2026-08-24 11:28:21.630191

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3ddaf7271fc3"
down_revision = "d4027db95431"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.create_check_constraint(
            batch_op.f("ck_user_oauth_superuser_is_not_guest"),
            "NOT (is_superuser AND is_guest)",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("ck_user_oauth_superuser_is_not_guest"), type_="check"
        )

    # ### end Alembic commands ###
