"""Make TaskGroup.path unique

Revision ID: 418477863093
Revises: b1e7f7a1ff71
Create Date: 2025-06-12 10:17:33.416416

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "418477863093"
down_revision = "b1e7f7a1ff71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_taskgroupv2_path"), ["path"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_taskgroupv2_path"), type_="unique"
        )

    # ### end Alembic commands ###
