"""Add task.args_schema

Revision ID: 46e70ccbc4f6
Revises: bb1cca2acc40
Create Date: 2023-05-23 16:32:21.078267

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "46e70ccbc4f6"
down_revision = "bb1cca2acc40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("args_schema", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "args_schema")
    # ### end Alembic commands ###
