"""TMP - is_v2_compatible

Revision ID: 4b35c5cefbe3
Revises: 876f28db9d4e
Create Date: 2024-03-28 15:26:33.436724

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "4b35c5cefbe3"
down_revision = "876f28db9d4e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_v2_compatible",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_column("is_v2_compatible")

    # ### end Alembic commands ###
