"""Add TaskGroupActivityV2

Revision ID: 57faddb94433
Revises: 19eca0dd47a9
Create Date: 2024-11-05 12:16:08.665424

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "57faddb94433"
down_revision = "19eca0dd47a9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskgroupactivityv2",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("taskgroupv2_id", sa.Integer(), nullable=True),
        sa.Column(
            "timestamp_started", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "pkg_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("log", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "timestamp_ended", sa.DateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["taskgroupv2_id"],
            ["taskgroupv2.id"],
            name=op.f("fk_taskgroupactivityv2_taskgroupv2_id_taskgroupv2"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_oauth.id"],
            name=op.f("fk_taskgroupactivityv2_user_id_user_oauth"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taskgroupactivityv2")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taskgroupactivityv2")
    # ### end Alembic commands ###
