"""Add WorkflowTemplate table

Revision ID: 59820266be0a
Revises: 6d679918c883
Create Date: 2026-02-16 15:26:25.120609

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "59820266be0a"
down_revision = "6d679918c883"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workflowtemplate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "timestamp_created", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "timestamp_last_used", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("user_group_id", sa.Integer(), nullable=True),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "data", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["usergroup.id"],
            name=op.f("fk_workflowtemplate_user_group_id_usergroup"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_oauth.id"],
            name=op.f("fk_workflowtemplate_user_id_user_oauth"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflowtemplate")),
    )
    with op.batch_alter_table("workflowtemplate", schema=None) as batch_op:
        batch_op.create_index(
            "ix_workflowtemplate_user_name_version_unique_constraint",
            ["user_id", "name", "version"],
            unique=True,
        )

    with op.batch_alter_table("workflowv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("template_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_workflowv2_template_id_workflowtemplate"),
            "workflowtemplate",
            ["template_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_workflowv2_template_id_workflowtemplate"),
            type_="foreignkey",
        )
        batch_op.drop_column("template_id")

    with op.batch_alter_table("workflowtemplate", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_workflowtemplate_user_name_version_unique_constraint"
        )

    op.drop_table("workflowtemplate")
    # ### end Alembic commands ###
