"""Task JSON non-sql-nullable

Revision ID: 5c1abd161cda
Revises: b1e7f7a1ff71
Create Date: 2025-06-18 15:22:07.518983

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5c1abd161cda"
down_revision = "b1e7f7a1ff71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "args_schema_non_parallel",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        )
        batch_op.alter_column(
            "args_schema_parallel",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "args_schema_parallel",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        )
        batch_op.alter_column(
            "args_schema_non_parallel",
            existing_type=postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
        )

    # ### end Alembic commands ###
