"""complete user-settings separation

Revision ID: 5f01747a9e09
Revises: e1575a65e853
Create Date: 2024-09-23 11:33:43.415807

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f01747a9e09"
down_revision = "e1575a65e853"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.alter_column(
            "user_settings_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_column("cache_dir")
        batch_op.drop_column("slurm_user")
        batch_op.drop_column("slurm_accounts")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "slurm_accounts",
                postgresql.JSON(astext_type=sa.Text()),
                server_default=sa.text("'[]'::json"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "slurm_user", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "cache_dir", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )
        batch_op.alter_column(
            "user_settings_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
