"""drop TaskV2.source

Revision ID: 5fb08bf05b14
Revises: e53dc51fdf93
Create Date: 2026-01-21 12:50:39.072816

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5fb08bf05b14"
down_revision = "e53dc51fdf93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.drop_column("source")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "source", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
