"""Add TaskGroupActivityV2

Revision ID: 606d4df56483
Revises: 8e8f227a3e36
Create Date: 2024-11-04 15:51:44.237939

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "606d4df56483"
down_revision = "8e8f227a3e36"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "taskgroupactivityv2",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("taskgroupv2_id", sa.Integer(), nullable=True),
        sa.Column(
            "timestamp_started", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "action", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("log", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "timestamp_ended", sa.DateTime(timezone=True), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["taskgroupv2_id"],
            ["taskgroupv2.id"],
            name=op.f("fk_taskgroupactivityv2_taskgroupv2_id_taskgroupv2"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_taskgroupactivityv2")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("taskgroupactivityv2")
    # ### end Alembic commands ###
