"""Update user and task

Revision ID: 62f2f0c4ac49
Revises: bb1cca2acc40
Create Date: 2023-05-24 12:38:43.871007

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "62f2f0c4ac49"
down_revision = "bb1cca2acc40"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "task",
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "user_oauth",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_oauth", "username")
    op.drop_column("task", "version")
    op.drop_column("task", "owner")
    # ### end Alembic commands ###
