"""add HistoryUnit.has_warnings

Revision ID: 635d07f1ab55
Revises: 1ef3722b998f
Create Date: 2026-05-25 10:05:31.756452

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "635d07f1ab55"
down_revision = "1ef3722b998f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyunit", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "has_warnings",
                sa.BOOLEAN(),
                server_default="false",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyunit", schema=None) as batch_op:
        batch_op.drop_column("has_warnings")

    # ### end Alembic commands ###
