"""Add unique constraint for task name

Revision ID: 66f492f489c3
Revises: 635d07f1ab55
Create Date: 2026-06-11 09:46:42.021186

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "66f492f489c3"
down_revision = "635d07f1ab55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.create_index(
            "ix_taskv2_one_task_name_per_task_group",
            ["name", "taskgroupv2_id"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.drop_index("ix_taskv2_one_task_name_per_task_group")

    # ### end Alembic commands ###
