"""Add task.owner, task.version and useroauth.username

Revision ID: 72dd911f94bb
Revises: 46e70ccbc4f6
Create Date: 2023-05-29 10:54:39.251667

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "72dd911f94bb"
down_revision = "46e70ccbc4f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "task",
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "user_oauth",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_oauth", "username")
    op.drop_column("task", "version")
    op.drop_column("task", "owner")
    # ### end Alembic commands ###
