"""index

Revision ID: 73f46a7aea34
Revises: e50b7b499e9c
Create Date: 2025-09-29 16:47:23.955594

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "73f46a7aea34"
down_revision = "e50b7b499e9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("faketable", schema=None) as batch_op:
        batch_op.create_index(
            "fancy_name",
            ["a"],
            unique=True,
            postgresql_where=sa.text("b IS TRUE"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("faketable", schema=None) as batch_op:
        batch_op.drop_index(
            "fancy_name", postgresql_where=sa.text("b IS TRUE")
        )

    # ### end Alembic commands ###
