"""add profile name

Revision ID: 74e9b7fd1945
Revises: 8ce0d43ced54
Create Date: 2025-10-14 15:50:43.718530

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "74e9b7fd1945"
down_revision = "8ce0d43ced54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_column("name")

    # ### end Alembic commands ###
