"""case6_add_fk

Revision ID: 79a5ef37ffcf
Revises: d2d558fec5f7
Create Date: 2023-06-28 10:21:54.125435

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "79a5ef37ffcf"
down_revision = "d2d558fec5f7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("fake_dataset_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            None, "dataset", ["fake_dataset_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("fake_dataset_id")

    # ### end Alembic commands ###
