"""JSONB default null

Revision ID: 79aa0d9ebd5c
Revises: b3ffb095f973
Create Date: 2025-06-19 16:25:47.356218

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "79aa0d9ebd5c"
down_revision = "b3ffb095f973"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "args_schema_non_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'null'::jsonb"),
        )
        batch_op.alter_column(
            "args_schema_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'null'::jsonb"),
        )

    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "meta_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'null'::jsonb"),
        )
        batch_op.alter_column(
            "meta_non_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'null'::jsonb"),
        )
        batch_op.alter_column(
            "args_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'null'::jsonb"),
        )
        batch_op.alter_column(
            "args_non_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'null'::jsonb"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "args_non_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )
        batch_op.alter_column(
            "args_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )
        batch_op.alter_column(
            "meta_non_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )
        batch_op.alter_column(
            "meta_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )

    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "args_schema_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )
        batch_op.alter_column(
            "args_schema_non_parallel",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )

    # ### end Alembic commands ###
