"""job id in history run

Revision ID: 7ca6b8fb96f9
Revises: 9db60297b8b2
Create Date: 2025-04-14 15:47:18.633542

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7ca6b8fb96f9"
down_revision = "9db60297b8b2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyrun", schema=None) as batch_op:
        batch_op.add_column(sa.Column("job_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_historyrun_job_id_jobv2"),
            "jobv2",
            ["job_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyrun", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_historyrun_job_id_jobv2"), type_="foreignkey"
        )
        batch_op.drop_column("job_id")

    # ### end Alembic commands ###
