"""Project sharing

Revision ID: 7e9963208a18
Revises: e0e717ae2f26
Create Date: 2025-11-20 11:27:21.734842

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e9963208a18"
down_revision = "e0e717ae2f26"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_owner", sa.BOOLEAN(), server_default="true", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_verified",
                sa.BOOLEAN(),
                server_default="true",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "permissions", sa.String(), server_default="rwx", nullable=False
            )
        )
        batch_op.create_index(
            "ix_linkuserprojectv2_one_owner_per_project",
            ["project_id"],
            unique=True,
            postgresql_where=sa.text("is_owner IS true"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_linkuserprojectv2_one_owner_per_project",
            postgresql_where=sa.text("is_owner IS true"),
        )
        batch_op.drop_column("permissions")
        batch_op.drop_column("is_verified")
        batch_op.drop_column("is_owner")

    # ### end Alembic commands ###
