"""project sharing

Revision ID: 80d283644fe7
Revises: 981d588fe248
Create Date: 2025-09-30 15:43:17.451606

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "80d283644fe7"
down_revision = "981d588fe248"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_owner",
                sa.Boolean(),
                server_default=sa.text("true"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_verified",
                sa.Boolean(),
                server_default=sa.text("true"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "can_write",
                sa.Boolean(),
                server_default=sa.text("true"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "can_execute",
                sa.Boolean(),
                server_default=sa.text("true"),
                nullable=False,
            )
        )
        batch_op.create_index(
            "idx_max_one_owner_per_project",
            ["project_id"],
            unique=True,
            postgresql_where=sa.text("is_owner IS true"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.drop_index(
            "idx_max_one_owner_per_project",
            postgresql_where=sa.text("is_owner IS true"),
        )
        batch_op.drop_column("can_execute")
        batch_op.drop_column("can_write")
        batch_op.drop_column("is_verified")
        batch_op.drop_column("is_owner")

    # ### end Alembic commands ###
