"""move from usersettings to profile

Revision ID: 82f37eb78240
Revises: 60771b110f78
Create Date: 2025-10-10 09:56:57.261038

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "82f37eb78240"
down_revision = "60771b110f78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "jobs_remote_dir",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "tasks_remote_dir",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )

    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("ssh_jobs_dir")
        batch_op.drop_column("ssh_tasks_dir")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ssh_tasks_dir",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "ssh_jobs_dir",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_column("tasks_remote_dir")
        batch_op.drop_column("jobs_remote_dir")

    # ### end Alembic commands ###
