"""Update TaskGroupActivityV2

Revision ID: 833feb19aa5e
Revises: 606d4df56483
Create Date: 2024-11-05 11:43:43.786357

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "833feb19aa5e"
down_revision = "606d4df56483"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupactivityv2", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column(
                "package", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_taskgroupactivityv2_user_id_user_oauth"),
            "user_oauth",
            ["user_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupactivityv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_taskgroupactivityv2_user_id_user_oauth"),
            type_="foreignkey",
        )
        batch_op.drop_column("version")
        batch_op.drop_column("package")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
