"""case4_rm_nullable

Revision ID: 8372224120ba
Revises: bf239a64907a
Create Date: 2023-06-28 10:11:08.743435

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8372224120ba"
down_revision = "bf239a64907a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###
