"""add applyworkflow.working_dir_user and remove task.project_id

Revision ID: 87d81daad178
Revises: fff40bbc0dc0
Create Date: 2023-02-01 15:44:42.691205

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "87d81daad178"
down_revision = "fff40bbc0dc0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applyworkflow",
        sa.Column(
            "working_dir_user",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.drop_constraint(None, "task", type_="foreignkey")
    op.drop_column("task", "project_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("project_id", sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, "task", "project", ["project_id"], ["id"])
    op.drop_column("applyworkflow", "working_dir_user")
    # ### end Alembic commands ###
