"""add_prevent_new_submissions

Revision ID: 88270f589c9b
Revises: f0702066b007
Create Date: 2025-12-02 12:34:11.028259

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88270f589c9b"
down_revision = "f0702066b007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "prevent_new_submissions",
                sa.BOOLEAN(),
                server_default="false",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_column("prevent_new_submissions")

    # ### end Alembic commands ###
