"""remove from usersettings

Revision ID: 8bb61d9299ab
Revises: 60771b110f78
Create Date: 2025-10-09 16:31:07.555897

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8bb61d9299ab"
down_revision = "60771b110f78"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("ssh_tasks_dir")
        batch_op.drop_column("ssh_jobs_dir")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "ssh_jobs_dir",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "ssh_tasks_dir",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
