"""resource constraints and fk

Revision ID: 8ce0d43ced54
Revises: 82f37eb78240
Create Date: 2025-10-13 14:24:01.541393

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "8ce0d43ced54"
down_revision = "82f37eb78240"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("resource_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_projectv2_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_resource_name"), ["name"]
        )

    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("resource_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_oauth_profile_id_profile"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_user_oauth_profile_id_profile"),
            "profile",
            ["profile_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_oauth_profile_id_profile"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_user_oauth_profile_id_profile"),
            "profile",
            ["profile_id"],
            ["id"],
        )

    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            type_="foreignkey",
        )
        batch_op.drop_column("resource_id")

    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_resource_name"), type_="unique"
        )

    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_projectv2_resource_id_resource"), type_="foreignkey"
        )
        batch_op.drop_column("resource_id")

    # ### end Alembic commands ###
