"""drop useroauth.username

Revision ID: 90f6508c6379
Revises: a80ac5a352bf
Create Date: 2025-10-15 16:09:40.922407

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "90f6508c6379"
down_revision = "a80ac5a352bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_column("username")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "username", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )

    # ### end Alembic commands ###
