"""add ondelete set null

Revision ID: 92ec661b7f76
Revises: 1ef3722b998f
Create Date: 2026-05-27 16:17:51.573205

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "92ec661b7f76"
down_revision = "1ef3722b998f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accountingrecordslurm", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_accountingrecordslurm_resource_id_resource"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_accountingrecordslurm_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accountingrecordslurm", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_accountingrecordslurm_resource_id_resource"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_accountingrecordslurm_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
        )

    # ### end Alembic commands ###
