"""TMP - WorkflowTaskV2.type in DB

Revision ID: 974c802f0dd0
Revises: e3e639454d4b
Create Date: 2024-04-02 11:21:20.212530

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "974c802f0dd0"
down_revision = "e3e639454d4b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "task_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.drop_column("task_type")

    # ### end Alembic commands ###
