"""drop taskv2.source uniqueness

Revision ID: 98486a7ae0b0
Revises: d82ee0dc1e48
Create Date: 2024-10-09 15:40:48.367151

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "98486a7ae0b0"
down_revision = "d82ee0dc1e48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        if op.get_bind().dialect.name == "sqlite":
            batch_op.create_unique_constraint("uq_taskv2_source", ["source"])

    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.drop_constraint("uq_taskv2_source", type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_taskv2_source", ["source"])

    # ### end Alembic commands ###
