"""“Add_linkusergroup_table”

Revision ID: 984d0381ccf7
Revises: 7c071e85cdf8
Create Date: 2024-09-09 11:41:53.047265

"""
import sqlalchemy as sa
import sqlmodel  # noqa
from alembic import op


# revision identifiers, used by Alembic.
revision = "984d0381ccf7"
down_revision = "7c071e85cdf8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linkusergroup",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["usergroup.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_oauth.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linkusergroup")
    # ### end Alembic commands ###
