"""drop old filter columns

Revision ID: 9bbd9b34a60a
Revises: db09233ad13a
Create Date: 2025-01-29 16:26:10.884466

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9bbd9b34a60a"
down_revision = "db09233ad13a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.drop_column("filters")

    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.drop_column("input_filters")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "input_filters",
                postgresql.JSON(astext_type=sa.Text()),
                server_default=sa.text("'null'::json"),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "filters",
                postgresql.JSON(astext_type=sa.Text()),
                server_default=sa.text("'null'::json"),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
