"""TMP - WorkflowTaskV2

Revision ID: 9cd305cd6023
Revises: a6231ed6273c
Create Date: 2024-03-26 09:15:00.188036

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = "9cd305cd6023"
down_revision = "a6231ed6273c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("args_parallel", sa.JSON(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("args_non_parallel", sa.JSON(), nullable=True)
        )
        batch_op.drop_column("args")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(sa.Column("args", sqlite.JSON(), nullable=True))
        batch_op.drop_column("args_non_parallel")
        batch_op.drop_column("args_parallel")

    # ### end Alembic commands ###
