"""Add DatasetV2.tags

Revision ID: a1f9ef8750f3
Revises: 0016fee8b597
Create Date: 2026-04-22 11:19:02.529567

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a1f9ef8750f3"
down_revision = "0016fee8b597"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags",
                postgresql.ARRAY(sa.String()),
                server_default="{}",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.drop_column("tags")

    # ### end Alembic commands ###
