"""2.17.1

Revision ID: a3602625d772
Revises: 83bc2ad3ffcc
Create Date: 2025-11-07 14:35:12.986904

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a3602625d772"
down_revision = "83bc2ad3ffcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_settings")
    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.alter_column(
            "resource_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.alter_column(
            "resource_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_user_oauth_user_settings_id_user_settings"),
            type_="foreignkey",
        )
        batch_op.drop_column("user_settings_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "user_settings_id",
                sa.INTEGER(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_user_oauth_user_settings_id_user_settings"),
            "user_settings",
            ["user_settings_id"],
            ["id"],
        )

    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.alter_column(
            "resource_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.alter_column(
            "resource_id", existing_type=sa.INTEGER(), nullable=True
        )

    op.create_table(
        "user_settings",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "slurm_accounts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "ssh_host", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ssh_username", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ssh_private_key_path",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "ssh_tasks_dir", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "ssh_jobs_dir", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "slurm_user", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "project_dir", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
    )
    # ### end Alembic commands ###
