"""add profile.resource_type

Revision ID: a51b834e85ac
Revises: 8ce0d43ced54
Create Date: 2025-10-15 14:14:57.484911

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "a51b834e85ac"
down_revision = "8ce0d43ced54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "resource_type",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_column("resource_type")

    # ### end Alembic commands ###
