"""Update type filters

Revision ID: a726e73048c9
Revises: fbce16ff4e47
Create Date: 2025-03-26 08:38:05.790272

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a726e73048c9"
down_revision = "fbce16ff4e47"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.drop_column("type_filters")

    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type_filters", sa.JSON(), server_default="{}", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.drop_column("type_filters")

    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type_filters",
                postgresql.JSON(astext_type=sa.Text()),
                server_default=sa.text("'{}'::json"),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
