"""Remove WorkflowTaskV2 legacy attributes

Revision ID: a75703146940
Revises: 5bf02391cfef
Create Date: 2024-09-03 10:34:51.761372

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a75703146940"
down_revision = "5bf02391cfef"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "workflowtaskv2", "task_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.drop_constraint(
        "fk_workflowtaskv2_task_legacy_id_task",
        "workflowtaskv2",
        type_="foreignkey",
    )
    op.drop_column("workflowtaskv2", "task_legacy_id")
    op.drop_column("workflowtaskv2", "is_legacy_task")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workflowtaskv2",
        sa.Column("is_legacy_task", sa.BOOLEAN(), nullable=False),
    )
    op.add_column(
        "workflowtaskv2",
        sa.Column("task_legacy_id", sa.INTEGER(), nullable=True),
    )
    op.create_foreign_key(
        "fk_workflowtaskv2_task_legacy_id_task",
        "workflowtaskv2",
        "task",
        ["task_legacy_id"],
        ["id"],
    )
    op.alter_column(
        "workflowtaskv2", "task_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
