"""Modify taskv2.source

Revision ID: a9fdbd13f6f8
Revises: 20128e9ad86d
Create Date: 2024-10-09 14:12:22.457795

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a9fdbd13f6f8"
down_revision = "20128e9ad86d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.drop_constraint("uq_taskv2_source", type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_taskv2_source", ["source"])
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###
