"""Drop ApplyWorkflow.overwrite_input

Revision ID: abe062fb6b4c
Revises: e8f4051440be
Create Date: 2023-05-11 16:52:36.816507

"""
# revision identifiers, used by Alembic.
revision = "abe062fb6b4c"
down_revision = "e8f4051440be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
