"""Pixi version to TaskGroup

Revision ID: b1e7f7a1ff71
Revises: 969d84257cac
Create Date: 2025-05-29 16:31:17.565973

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "b1e7f7a1ff71"
down_revision = "969d84257cac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pixi_version",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "wheel_path", nullable=True, new_column_name="archive_path"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.alter_column(
            "archive_path", nullable=True, new_column_name="wheel_path"
        )
        batch_op.drop_column("pixi_version")

    # ### end Alembic commands ###
