"""new history tables

Revision ID: b2fa5e3521e8
Revises: 954ddc64425a
Create Date: 2025-03-13 15:28:28.352141

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b2fa5e3521e8"
down_revision = "954ddc64425a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historyrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("workflowtask_id", sa.Integer(), nullable=True),
        sa.Column(
            "workflowtask_dump",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "task_group_dump",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "timestamp_started", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("num_current_images", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasetv2.id"],
            name=op.f("fk_historyrun_dataset_id_datasetv2"),
        ),
        sa.ForeignKeyConstraint(
            ["workflowtask_id"],
            ["workflowtaskv2.id"],
            name=op.f("fk_historyrun_workflowtask_id_workflowtaskv2"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historyrun")),
    )
    op.create_table(
        "historyunit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("history_run_id", sa.Integer(), nullable=False),
        sa.Column(
            "logfile", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("zarr_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["history_run_id"],
            ["historyrun.id"],
            name=op.f("fk_historyunit_history_run_id_historyrun"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historyunit")),
    )
    op.create_table(
        "historyimagecache",
        sa.Column(
            "zarr_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("workflowtask_id", sa.Integer(), nullable=False),
        sa.Column("history_unit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasetv2.id"],
            name=op.f("fk_historyimagecache_dataset_id_datasetv2"),
        ),
        sa.ForeignKeyConstraint(
            ["history_unit_id"],
            ["historyunit.id"],
            name=op.f("fk_historyimagecache_history_unit_id_historyunit"),
        ),
        sa.ForeignKeyConstraint(
            ["workflowtask_id"],
            ["workflowtaskv2.id"],
            name=op.f("fk_historyimagecache_workflowtask_id_workflowtaskv2"),
        ),
        sa.PrimaryKeyConstraint(
            "zarr_url",
            "dataset_id",
            "workflowtask_id",
            name=op.f("pk_historyimagecache"),
        ),
    )
    op.drop_table("historyitemv2")
    op.drop_table("imagestatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "imagestatus",
        sa.Column(
            "zarr_url", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "workflowtask_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "dataset_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "parameters_hash",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("logfile", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasetv2.id"],
            name="fk_imagestatus_dataset_id_datasetv2",
        ),
        sa.ForeignKeyConstraint(
            ["workflowtask_id"],
            ["workflowtaskv2.id"],
            name="fk_imagestatus_workflowtask_id_workflowtaskv2",
        ),
        sa.PrimaryKeyConstraint(
            "zarr_url", "workflowtask_id", "dataset_id", name="pk_imagestatus"
        ),
    )
    op.create_table(
        "historyitemv2",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "dataset_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "workflowtask_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "timestamp_started",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "workflowtask_dump",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "task_group_dump",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "parameters_hash",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "num_available_images",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "num_current_images",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "images",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasetv2.id"],
            name="fk_historyitemv2_dataset_id_datasetv2",
        ),
        sa.ForeignKeyConstraint(
            ["workflowtask_id"],
            ["workflowtaskv2.id"],
            name="fk_historyitemv2_workflowtask_id_workflowtaskv2",
        ),
        sa.PrimaryKeyConstraint("id", name="pk_historyitemv2"),
    )
    op.drop_table("historyimagecache")
    op.drop_table("historyunit")
    op.drop_table("historyrun")
    # ### end Alembic commands ###
