"""Task and Workflowtask JSON non nulable

Revision ID: b3198af18e71
Revises: b1e7f7a1ff71
Create Date: 2025-06-16 15:10:03.563631

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b3198af18e71'
down_revision = 'b1e7f7a1ff71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('taskv2', schema=None) as batch_op:
        batch_op.alter_column('args_schema_non_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default="{}",)
        batch_op.alter_column('args_schema_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default="{}",)

    with op.batch_alter_table('workflowtaskv2', schema=None) as batch_op:
        batch_op.alter_column('meta_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default="{}",)
        batch_op.alter_column('meta_non_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               server_default="{}",)
        batch_op.alter_column('args_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False, server_default="{}",)
        batch_op.alter_column('args_non_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False, server_default="{}",)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflowtaskv2', schema=None) as batch_op:
        batch_op.alter_column('args_non_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('args_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('meta_non_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('meta_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('taskv2', schema=None) as batch_op:
        batch_op.alter_column('args_schema_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('args_schema_non_parallel',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    # ### end Alembic commands ###
