"""split filters and keep old columns

Revision ID: b6e34fcadf76
Revises: 316140ff7ee1
Create Date: 2025-01-07 17:00:11.918316

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "b6e34fcadf76"
down_revision = "316140ff7ee1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type_filters", sa.JSON(), server_default="{}", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "attribute_filters",
                sa.JSON(),
                server_default="{}",
                nullable=False,
            )
        )

    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type_filters", sa.JSON(), server_default="{}", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.drop_column("type_filters")

    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.drop_column("attribute_filters")
        batch_op.drop_column("type_filters")

    # ### end Alembic commands ###
