"""2.18.1

Revision ID: b7477cc98f45
Revises: 88270f589c9b
Create Date: 2025-12-04 14:07:27.954252

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7477cc98f45"
down_revision = "88270f589c9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_column("project_dir")

        # ### end Alembic commands ###

        batch_op.alter_column("project_dirs", server_default=None)

    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.alter_column("is_owner", server_default=None)
        batch_op.alter_column("is_verified", server_default=None)
        batch_op.alter_column("permissions", server_default=None)


def downgrade() -> None:
    with op.batch_alter_table("linkuserprojectv2", schema=None) as batch_op:
        batch_op.alter_column("permissions", server_default="rwx")
        batch_op.alter_column("is_verified", server_default="true")
        batch_op.alter_column("is_owner", server_default="true")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "project_dir", sa.VARCHAR(), autoincrement=False, nullable=True
            )
        )

        # ### end Alembic commands ###

        batch_op.alter_column("project_dirs", server_default="{}")
