"""venv info in task group

Revision ID: bae253fd2247
Revises: c94ec879e2e6
Create Date: 2024-11-12 09:07:23.474821

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bae253fd2247"
down_revision = "c94ec879e2e6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("venv_size_in_kB", sa.Integer(), nullable=True)
        )
        batch_op.add_column(
            sa.Column("venv_file_number", sa.Integer(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_column("venv_file_number")
        batch_op.drop_column("venv_size")

    # ### end Alembic commands ###
