"""add ApplyWorkflow.end_timestamp

Revision ID: bb1cca2acc40
Revises: fda995215ae9
Create Date: 2023-05-12 10:15:50.102921

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bb1cca2acc40"
down_revision = "fda995215ae9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applyworkflow",
        sa.Column("end_timestamp", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applyworkflow", "end_timestamp")
    # ### end Alembic commands ###
