"""add fractal_server_version column to JobV2 and TaskGroupActivityV2

Revision ID: bb5d46d6158c
Revises: 18a26fcdea5d
Create Date: 2026-01-29 11:54:37.244069

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "bb5d46d6158c"
down_revision = "18a26fcdea5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fractal_server_version",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )

    with op.batch_alter_table("taskgroupactivityv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fractal_server_version",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupactivityv2", schema=None) as batch_op:
        batch_op.drop_column("fractal_server_version")

    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.drop_column("fractal_server_version")

    # ### end Alembic commands ###
