"""case3_mk_nullable

Revision ID: bf239a64907a
Revises: cc85a24272c7
Create Date: 2023-06-28 10:04:28.870913

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "bf239a64907a"
down_revision = "cc85a24272c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###
