"""add ProjectV2.description

Revision ID: c0448884a8e9
Revises: 18867fb5201a
Create Date: 2026-05-21 11:11:53.512153

"""

import sqlalchemy as sa
from alembic import op

from fractal_server.migrations.sqltypes import AutoString

# revision identifiers, used by Alembic.
revision = "c0448884a8e9"
down_revision = "18867fb5201a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", AutoString(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.drop_column("description")

    # ### end Alembic commands ###
