"""remove old filter columns

Revision ID: c16108de9f77
Revises: f5aed9bbae62
Create Date: 2025-01-07 17:36:56.520295

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c16108de9f77"
down_revision = "f5aed9bbae62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.drop_column("filters")

    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.drop_column("input_filters")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "input_filters",
                postgresql.JSON(astext_type=sa.Text()),
                server_default=sa.text(
                    '\'{"attributes": {}, "types": {}}\'::json'
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "filters",
                postgresql.JSON(astext_type=sa.Text()),
                server_default=sa.text(
                    '\'{"attributes": {}, "types": {}}\'::json'
                ),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
