"""new taskgroup attributes

Revision ID: c58106a58cc5
Revises: 7cbbb4fbb940
Create Date: 2024-10-07 14:44:49.215486

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "c58106a58cc5"
down_revision = "7cbbb4fbb940"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "origin", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "pkg_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "version", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "python_version",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "path", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "venv_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "pip_extras", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_column("pip_extras")
        batch_op.drop_column("venv_path")
        batch_op.drop_column("path")
        batch_op.drop_column("python_version")
        batch_op.drop_column("version")
        batch_op.drop_column("pkg_name")
        batch_op.drop_column("origin")

    # ### end Alembic commands ###
