"""add constraint to resource table

Revision ID: c7e5a5b8f6a1
Revises: 82f37eb78240
Create Date: 2025-10-13 10:14:21.111011

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "c7e5a5b8f6a1"
down_revision = "82f37eb78240"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_resource_name"), ["name"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_resource_name"), type_="unique"
        )

    # ### end Alembic commands ###
