"""nullable jobs_poll_interval

Revision ID: cb7fe4a87355
Revises: 8ce0d43ced54
Create Date: 2025-10-13 16:56:42.436825

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "cb7fe4a87355"
down_revision = "8ce0d43ced54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.alter_column(
            "jobs_poll_interval", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("resource", schema=None) as batch_op:
        batch_op.alter_column(
            "jobs_poll_interval", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
