"""case2_rm_unique

Revision ID: cc85a24272c7
Revises: dd0f8a1b064f
Create Date: 2023-06-28 09:33:18.718491

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "cc85a24272c7"
down_revision = "dd0f8a1b064f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_constraint("uq_task_source", type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_task_source", ["source"])

    # ### end Alembic commands ###
