"""add resource_id fk to project and task_group

Revision ID: ced1c324de56
Revises: c7e5a5b8f6a1
Create Date: 2025-10-13 12:17:07.551136

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "ced1c324de56"
down_revision = "c7e5a5b8f6a1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("resource_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_projectv2_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("resource_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            type_="foreignkey",
        )
        batch_op.drop_column("resource_id")

    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_projectv2_resource_id_resource"), type_="foreignkey"
        )
        batch_op.drop_column("resource_id")

    # ### end Alembic commands ###
