"""add fractal_server_version to jobv2 and taskgroupactivityv2

Revision ID: cfd13f7954e7
Revises: 18a26fcdea5d
Create Date: 2026-01-29 12:33:00.064562

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cfd13f7954e7"
down_revision = "18a26fcdea5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fractal_server_version",
                sa.String(),
                server_default="pre-2.19.0",
                nullable=False,
            )
        )

    with op.batch_alter_table("taskgroupactivityv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "fractal_server_version",
                sa.String(),
                server_default="pre-2.19.0",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupactivityv2", schema=None) as batch_op:
        batch_op.drop_column("fractal_server_version")

    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.drop_column("fractal_server_version")

    # ### end Alembic commands ###
