"""Expand TaskGroup and drop unique-source TaskV2 constraint

Revision ID: d22a65f96036
Revises: d82ee0dc1e48
Create Date: 2024-10-09 16:30:18.492460

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "d22a65f96036"
down_revision = "d82ee0dc1e48"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "wheel_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "pinned_package_versions",
                sa.JSON(),
                server_default="{}",
                nullable=True,
            )
        )

    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=True
        )
        batch_op.drop_constraint("uq_taskv2_source", type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_taskv2_source", ["source"])
        batch_op.alter_column(
            "source", existing_type=sa.VARCHAR(), nullable=False
        )

    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_column("pinned_package_versions")
        batch_op.drop_column("wheel_path")

    # ### end Alembic commands ###
