"""Add new history tables

Revision ID: d36afe65c612
Revises: af1ef1c83c9b
Create Date: 2025-03-14 11:44:24.803008

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d36afe65c612"
down_revision = "af1ef1c83c9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "historyrun",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("workflowtask_id", sa.Integer(), nullable=True),
        sa.Column(
            "workflowtask_dump",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "task_group_dump",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column(
            "timestamp_started", sa.DateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("num_current_images", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasetv2.id"],
            name=op.f("fk_historyrun_dataset_id_datasetv2"),
        ),
        sa.ForeignKeyConstraint(
            ["workflowtask_id"],
            ["workflowtaskv2.id"],
            name=op.f("fk_historyrun_workflowtask_id_workflowtaskv2"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historyrun")),
    )
    op.create_table(
        "historyunit",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("history_run_id", sa.Integer(), nullable=False),
        sa.Column(
            "logfile", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("zarr_urls", postgresql.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["history_run_id"],
            ["historyrun.id"],
            name=op.f("fk_historyunit_history_run_id_historyrun"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_historyunit")),
    )
    op.create_table(
        "historyimagecache",
        sa.Column(
            "zarr_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("workflowtask_id", sa.Integer(), nullable=False),
        sa.Column("latest_history_unit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasetv2.id"],
            name=op.f("fk_historyimagecache_dataset_id_datasetv2"),
        ),
        sa.ForeignKeyConstraint(
            ["latest_history_unit_id"],
            ["historyunit.id"],
            name=op.f(
                "fk_historyimagecache_latest_history_unit_id_historyunit"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["workflowtask_id"],
            ["workflowtaskv2.id"],
            name=op.f("fk_historyimagecache_workflowtask_id_workflowtaskv2"),
        ),
        sa.PrimaryKeyConstraint(
            "zarr_url",
            "dataset_id",
            "workflowtask_id",
            name=op.f("pk_historyimagecache"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("historyimagecache")
    op.drop_table("historyunit")
    op.drop_table("historyrun")
    # ### end Alembic commands ###
