"""Add pinned-package-versions to taskgroup

Revision ID: d4ce8d981090
Revises: 742b74e1cc6e
Create Date: 2024-10-08 13:09:44.020986

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d4ce8d981090"
down_revision = "742b74e1cc6e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "pinned_package_versions",
                sa.JSON(),
                server_default="{}",
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_column("pinned_package_versions")

    # ### end Alembic commands ###
