"""add user_oauth.slurm_accounts

Revision ID: d606f142074f
Revises: d4fe3708d309
Create Date: 2023-12-04 16:30:02.280879

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d606f142074f"
down_revision = "d4fe3708d309"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "slurm_accounts",
                sa.JSON(),
                server_default="[]",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_column("slurm_accounts")

    # ### end Alembic commands ###
