"""TaskGroup.resource_id not nullable

Revision ID: d82bb7137b2d
Revises: f65ee53991e3
Create Date: 2025-10-24 11:56:27.514548

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d82bb7137b2d"
down_revision = "f65ee53991e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.alter_column(
            "resource_id", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.drop_constraint(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_taskgroupv2_resource_id_resource"),
            "resource",
            ["resource_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.alter_column(
            "resource_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
