"""Remove UserGroup.viewer_paths

Revision ID: daa11beb3d09
Revises: ca52947a4fe2
Create Date: 2025-11-27 10:29:10.750937

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "daa11beb3d09"
down_revision = "ca52947a4fe2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usergroup", schema=None) as batch_op:
        batch_op.drop_column("viewer_paths")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("usergroup", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "viewer_paths",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default=sa.text("'[]'::json"),
                autoincrement=False,
                nullable=False,
            )
        )

    # ### end Alembic commands ###
