"""add TaskV2.is_core

Revision ID: daecd41f37da
Revises: 66f492f489c3
Create Date: 2026-06-09 15:33:27.850656

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "daecd41f37da"
down_revision = "66f492f489c3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_core", sa.BOOLEAN(), server_default="false", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskv2", schema=None) as batch_op:
        batch_op.drop_column("is_core")

    # ### end Alembic commands ###
