"""pixi version

Revision ID: daf2f94f4a0e
Revises: 969d84257cac
Create Date: 2025-05-28 23:01:46.463427

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "daf2f94f4a0e"
down_revision = "969d84257cac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pixiversion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "timestamp_created", sa.DateTime(timezone=True), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pixiversion")),
        sa.UniqueConstraint("path", name=op.f("uq_pixiversion_path")),
        sa.UniqueConstraint("version", name=op.f("uq_pixiversion_version")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pixiversion")
    # ### end Alembic commands ###
