"""example

Revision ID: db7d18dc890c
Revises: 7226c20dc233
Create Date: 2026-04-10 10:02:03.680110

"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "db7d18dc890c"
down_revision = "7226c20dc233"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "example_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_example")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("example")
    # ### end Alembic commands ###
