"""Add args_schema columns

Revision ID: dce3e2acbd3c
Revises: 50a13d6138fd
Create Date: 2023-06-06 09:13:47.481618

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "dce3e2acbd3c"
down_revision = "50a13d6138fd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("args_schema", sa.JSON(), nullable=True))
    op.add_column(
        "task",
        sa.Column(
            "args_schema_version",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "args_schema_version")
    op.drop_column("task", "args_schema")
    # ### end Alembic commands ###
