"""case1_add_unique

Revision ID: dd0f8a1b064f
Revises: f384e1c0cf5d
Create Date: 2023-06-28 09:30:14.237432

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "dd0f8a1b064f"
down_revision = "f384e1c0cf5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["input_type"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
