"""new user settings columns

Revision ID: e1575a65e853
Revises: dfbe4f3a7bc4
Create Date: 2024-09-19 12:14:38.481210

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "e1575a65e853"
down_revision = "dfbe4f3a7bc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "slurm_user", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "slurm_accounts",
                sa.JSON(),
                server_default="[]",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "cache_dir", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.drop_column("cache_dir")
        batch_op.drop_column("slurm_accounts")
        batch_op.drop_column("slurm_user")

    # ### end Alembic commands ###
