"""fake table

Revision ID: e50b7b499e9c
Revises: 981d588fe248
Create Date: 2025-09-29 16:27:34.878121

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "e50b7b499e9c"
down_revision = "981d588fe248"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faketable",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("a", sa.Integer(), nullable=False),
        sa.Column("b", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_faketable")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("faketable")
    # ### end Alembic commands ###
