"""add UserOAuth.is_guest

Revision ID: e53dc51fdf93
Revises: 068496367952
Create Date: 2026-01-14 14:32:25.044504

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e53dc51fdf93"
down_revision = "068496367952"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_guest", sa.BOOLEAN(), server_default="false", nullable=False
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.drop_column("is_guest")

    # ### end Alembic commands ###
