"""Add DatasetV2.tags

Revision ID: e6a4746ddcd2
Revises: 0016fee8b597
Create Date: 2026-04-22 09:04:09.707746

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e6a4746ddcd2"
down_revision = "0016fee8b597"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "tags",
                postgresql.JSONB(astext_type=sa.Text()),
                server_default="[]",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.drop_column("tags")

    # ### end Alembic commands ###
