"""Add unique constraints to TaskGroupV2

Revision ID: e8450ebe0634
Revises: cfd13f7954e7
Create Date: 2026-02-12 10:09:43.261107

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e8450ebe0634"
down_revision = "cfd13f7954e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.create_index(
            "ix_taskgroupv2_path_unique_constraint",
            ["path", "resource_id"],
            unique=True,
        )
        batch_op.create_index(
            "ix_taskgroupv2_user_unique_constraint",
            ["user_id", "pkg_name", "version", "resource_id"],
            unique=True,
            postgresql_nulls_not_distinct=True,
        )
        batch_op.create_index(
            "ix_taskgroupv2_usergroup_unique_constraint",
            ["user_group_id", "pkg_name", "version"],
            unique=True,
            postgresql_nulls_not_distinct=True,
            postgresql_where=sa.text("user_group_id IS NOT NULL"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("taskgroupv2", schema=None) as batch_op:
        batch_op.drop_index(
            "ix_taskgroupv2_usergroup_unique_constraint",
            postgresql_nulls_not_distinct=True,
            postgresql_where=sa.text("user_group_id IS NOT NULL"),
        )
        batch_op.drop_index(
            "ix_taskgroupv2_user_unique_constraint",
            postgresql_nulls_not_distinct=True,
        )
        batch_op.drop_index("ix_taskgroupv2_path_unique_constraint")

    # ### end Alembic commands ###
