"""fake-2-17-bis

Revision ID: e928a32b675b
Revises: 4b4c4d1104e7
Create Date: 2025-11-20 09:16:55.390723

"""

# revision identifiers, used by Alembic.
revision = "e928a32b675b"
down_revision = "4b4c4d1104e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
