"""split filters and keep old columns

Revision ID: ec7329221c1a
Revises: 316140ff7ee1
Create Date: 2025-01-08 15:46:26.940083

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec7329221c1a"
down_revision = "316140ff7ee1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type_filters", sa.JSON(), server_default="{}", nullable=False
            )
        )
        batch_op.add_column(
            sa.Column(
                "attribute_filters",
                sa.JSON(),
                server_default="{}",
                nullable=False,
            )
        )
        batch_op.alter_column(
            "filters",
            existing_type=sa.JSON(astext_type=sa.Text()),
            nullable=True,
            existing_server_default=sa.text(
                '\'{"attributes": {}, "types": {}}\'::json'
            ),
        )

    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "attribute_filters",
                sa.JSON(),
                server_default="{}",
                nullable=False,
            )
        )

    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type_filters", sa.JSON(), server_default="{}", nullable=False
            )
        )
        batch_op.alter_column(
            "input_filters",
            existing_type=sa.JSON(astext_type=sa.Text()),
            nullable=True,
            existing_server_default=sa.text(
                '\'{"attributes": {}, "types": {}}\'::json'
            ),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowtaskv2", schema=None) as batch_op:
        batch_op.alter_column(
            "input_filters",
            existing_type=sa.JSON(astext_type=sa.Text()),
            nullable=False,
            existing_server_default=sa.text(
                '\'{"attributes": {}, "types": {}}\'::json'
            ),
        )
        batch_op.drop_column("type_filters")

    with op.batch_alter_table("jobv2", schema=None) as batch_op:
        batch_op.drop_column("attribute_filters")

    with op.batch_alter_table("datasetv2", schema=None) as batch_op:
        batch_op.alter_column(
            "filters",
            existing_type=sa.JSON(astext_type=sa.Text()),
            nullable=False,
            existing_server_default=sa.text(
                '\'{"attributes": {}, "types": {}}\'::json'
            ),
        )
        batch_op.drop_column("attribute_filters")
        batch_op.drop_column("type_filters")

    # ### end Alembic commands ###
