"""add indexes

Revision ID: f2665468c4af
Revises: 969d84257cac
Create Date: 2025-05-30 17:32:01.105452

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "f2665468c4af"
down_revision = "969d84257cac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyimagecache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_historyimagecache_dataset_id"),
            ["dataset_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_historyimagecache_latest_history_unit_id"),
            ["latest_history_unit_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_historyimagecache_workflowtask_id"),
            ["workflowtask_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("historyimagecache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_historyimagecache_workflowtask_id"))
        batch_op.drop_index(
            batch_op.f("ix_historyimagecache_latest_history_unit_id")
        )
        batch_op.drop_index(batch_op.f("ix_historyimagecache_dataset_id"))

    # ### end Alembic commands ###
