"""add ProjectV2.is_starred and WorkflowV2.is_starred

Revision ID: f529d37a9210
Revises: 3e3ccea2f3ec
Create Date: 2026-05-14 12:48:34.747267

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f529d37a9210"
down_revision = "3e3ccea2f3ec"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_starred",
                sa.BOOLEAN(),
                server_default="false",
                nullable=False,
            )
        )

    with op.batch_alter_table("workflowv2", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_starred",
                sa.BOOLEAN(),
                server_default="false",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workflowv2", schema=None) as batch_op:
        batch_op.drop_column("is_starred")

    with op.batch_alter_table("projectv2", schema=None) as batch_op:
        batch_op.drop_column("is_starred")

    # ### end Alembic commands ###
