"""add Profile.name, make UserSettings.project_dir required

Revision ID: f541e114b489
Revises: 8ce0d43ced54
Create Date: 2025-10-14 17:13:30.740788

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision = "f541e114b489"
down_revision = "8ce0d43ced54"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
            )
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_profile_name"), ["name"]
        )

    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "project_dir", existing_type=sa.VARCHAR(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_settings", schema=None) as batch_op:
        batch_op.alter_column(
            "project_dir", existing_type=sa.VARCHAR(), nullable=True
        )

    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_profile_name"), type_="unique")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
