"""user-settings-related

Revision ID: f68960037f10
Revises: 90f6508c6379
Create Date: 2025-10-22 13:44:03.160849

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f68960037f10"
down_revision = "90f6508c6379"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "project_dir",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "slurm_accounts", postgresql.ARRAY(sa.String()), nullable=True
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_user_oauth_user_settings_id_user_settings"),
            type_="foreignkey",
        )
        batch_op.drop_column("user_settings_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_oauth", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "user_settings_id",
                sa.INTEGER(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_user_oauth_user_settings_id_user_settings"),
            "user_settings",
            ["user_settings_id"],
            ["id"],
        )
        batch_op.drop_column("slurm_accounts")
        batch_op.drop_column("project_dir")

    # ### end Alembic commands ###
