"""Drop ApplyWorkflow.overwrite_input

Revision ID: fda995215ae9
Revises: e8f4051440be
Create Date: 2023-05-11 17:02:46.208476

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "fda995215ae9"
down_revision = "e8f4051440be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("applyworkflow", "overwrite_input")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applyworkflow",
        sa.Column("overwrite_input", sa.BOOLEAN(), nullable=False),
    )
    # ### end Alembic commands ###
