"""Drop V1 tables

Revision ID: feba0b431c79
Revises: 8b2daaea466f
Create Date: 2025-01-29 15:55:55.622418

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "feba0b431c79"
down_revision = "8b2daaea466f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource")
    op.drop_table("applyworkflow")
    op.drop_table("task")
    op.drop_table("workflow")
    op.drop_table("workflowtask")
    op.drop_table("linkuserproject")
    op.drop_table("dataset")
    op.drop_table("project")
    op.drop_table("state")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "state",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_state"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_project"),
    )
    op.create_table(
        "dataset",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_dataset"),
    )
    op.create_table(
        "linkuserproject",
        sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_table(
        "workflowtask",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workflowtask"),
    )
    op.create_table(
        "workflow",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_workflow"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_task"),
    )
    op.create_table(
        "applyworkflow",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_applyworkflow"),
    )
    op.create_table(
        "resource",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name="pk_resource"),
    )
    # ### end Alembic commands ###
