name: alembic-check

on:
  push:
    branches: ["main", 'ihb-develop']
  pull_request:
    branches: ["main", 'ihb-develop']

permissions: {}

jobs:

  alembic-check:

    name: "alembic check"
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Start Postgres
        run: |
          sudo systemctl start postgresql.service
          sudo --login -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
          sudo --login -u postgres createdb fractal_test

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          version: "0.11.14"
          enable-cache: true

      - run: uv sync --frozen

      - name: Run alembic check
        env:
          JWT_SECRET_KEY: some_secret
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fractal_test
        run: |
          cd fractal_server
          uv run --frozen fractalctl set-db
          uv run --frozen alembic check
