name: alembic-check

on:
  push:
    branches: ["main", 'ihb-develop']
  pull_request:
    branches: ["main", 'ihb-develop']

permissions: {}

jobs:

  alembic-check:

    name: "alembic check"
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - name: Start Postgres
        run: |
          sudo systemctl start postgresql.service
          sudo --login -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
          sudo --login -u postgres createdb fractal_test

      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39
        with:
          version: "0.11.14"
          enable-cache: true
          python-version: "3.12"

      - run: uv sync --frozen

      - name: Run alembic check
        env:
          JWT_SECRET_KEY: some_secret
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fractal_test
        run: |
          cd fractal_server
          uv run --frozen fractalctl set-db
          uv run --frozen alembic check
