name: Build package

on:
  push:
    branches: ["main", 'ihb-develop']
  pull_request:
    branches: ["main", 'ihb-develop']

permissions: {}

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.12"

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          version: "0.9.24"
          enable-cache: true

      - run: uv build
