name: ci python next

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * 2"

permissions: {}

jobs:

  tests:

    name: "Python-next"
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.14"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: Start Postgres
        run: |
          sudo systemctl start postgresql.service
          sudo --login -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'postgres';"
          sudo --login -u postgres createdb fractal_test

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          version: "0.9.24"
          enable-cache: true

      - run: uv sync --frozen

      - name: Test with pytest
        run: uv run --frozen pytest -vv --durations 0 -m "not oauth and not basic_auth"
