name: docs

on:
  push:
    branches: ["main", 'ihb-develop']
  pull_request:
    branches: ["main", 'ihb-develop']

env:
  JWT_SECRET_KEY: "very_secret_key-very_secret_key-very_secret_key"
  POSTGRES_DB: fake
  OAUTH_CLIENT_NAME: oauth2-example
  OAUTH_CLIENT_ID: oidc_example_client_id
  OAUTH_CLIENT_SECRET: oicd_example_client_secret
  OAUTH_OIDC_CONFIG_ENDPOINT: https://accounts.google.com/.well-known/openid-configuration

permissions: {}

jobs:

  docs:
    name: "Deploy docs"
    runs-on: ubuntu-24.04
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      id-token: write

    steps:

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          version: "0.9.24"
          enable-cache: true
      - run: uv sync --frozen --group docs
      - run: uv run --frozen fractalctl openapi -f docs/openapi.json
      - run: uv run --frozen mkdocs gh-deploy --config-file mkdocs.yml --force --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docs-build:
    name: "Test docs build"
    runs-on: ubuntu-24.04
    if: ${{ github.event_name != 'push' || github.ref != 'refs/heads/main' }}
    permissions: {}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57
        with:
          version: "0.9.24"
          enable-cache: true
      - run: uv sync --frozen --group docs
      - run: uv run --frozen fractalctl openapi -f docs/openapi.json
      - run: uv run --frozen mkdocs build --config-file mkdocs.yml
