name: Publish docs

on:
  pull_request:
    branches:
      - main

jobs:

  build:

    name: Deploy docs
    runs-on: ubuntu-latest
    needs: coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download data
        uses: actions/download-artifact@v3
        with:
          name: html-report

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: docs/doc-requirements.txt
