name: Build package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

      - uses: actions/checkout@v5
        with:
          persist-credentials: false

      - name: "Set up Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Install poetry"
        run: pipx install poetry==2.2.1

      - name: Build package
        run: poetry build
