name: Publish on TestPyPI
on:
  push:
    tags:
      # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+[a-c][0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+alpha[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+beta[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  build_and_publish:
    runs-on: ubuntu-20.04
    environment: pypi
    steps:

      - name: Check that PYPI_TOKEN secret exists
        env:
            CURRENT_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN}}
        if: ${{ env.CURRENT_PYPI_TOKEN == '' }}
        run: echo "Secret PYPI_TOKEN is not defined." && exit 1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install poetry
        run: pipx install poetry==1.5

      - name: Build package
        run: poetry build --verbose

      - name: Publish to TestPyPI
        env:
          POETRY_PUBLISH_USERNAME: "__token__"
          POETRY_PUBLISH_PASSWORD: ${{ secrets.PYPI_TOKEN}}
        run: poetry publish --repository testpypi --username ${{ env.POETRY_PUBLISH_USERNAME }} --password ${{ env.POETRY_PUBLISH_PASSWORD }}
