HISTORY_FILENAME = "history.json"
TYPE_FILTERS_FILENAME = "type_filters.json"
ATTRIBUTE_FILTERS_FILENAME = "attribute_filters.json"
IMAGES_FILENAME = "images.json"
METADATA_FILENAME = "metadata.json"
SHUTDOWN_FILENAME = "shutdown"
WORKFLOW_LOG_FILENAME = "workflow.log"
